---

- console:
    enable: on

- epics:
    enable: on
    # $HOSTNAME: machine hostname
    prefix: "$hostname:SENS:"
    fpgatype: "artix7"

- http:
    enable: on
    url: "https://telegraf:8186/write"
    username: "myuser"
    password: "mypass"
