---

- console:
    enable: on

- epics:
    enable: on
    # $HOSTNAME: machine hostname
    prefix: "$hostname:SENS:"

- http:
    enable: on
    url: "http://changeme:1234"
    username: "foo"
    password: "bar"
