
pvdb = {

   'zynq7000': {

      'TEMP' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'C',
         'value': 0,
         'event': "xadc",
         'metric': ["temp"],
         'valattr': "value",
      },
      'VCCINT' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vccint"],
         'valattr': "value",
      },
      'VCCAUX' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vccaux"],
         'valattr': "value",
      },
      'VCCBRAM' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vccbram"],
         'valattr': "value",
      },
      'VCCPINT' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vccpint"],
         'valattr': "value",
      },
      'VCCPAUX' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vccpaux"],
         'valattr': "value",
      },
      'VCCODDR' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vccoddr"],
         'valattr': "value",
      },
      'VREFP' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vrefp"],
         'valattr': "value",
      },
      'VREFN' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vrefn"],
         'valattr': "value",
      },
      'IDCODETEST:RESULT' : {
         'type': 'int',
         'mdel': -1,
         'scan' : 1,
         'value': 0,
         'event': "idcode_test",
         'metric': ["jtag_only"],
         'valattr': "result",
      },
      'UPSETS' : {
         'type': 'int',
         'mdel': -1,
         'scan' : 1,
         'value': 0,
         'event': "count",
         'metric': ["rdcheck_complete", "emptycheck_complete", "overall"],
         'valattr': "upsets",
      },
      'FRAMES' : {
         'type': 'int',
         'mdel': -1,
         'scan' : 1,
         'value': 0,
         'event': "count",
         'metric': ["rdcheck_complete", "emptycheck_complete", "overall"],
         'valattr': "frames",
       },
   },          # end of zynq7000

   'artix7': {

      'TEMP' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'C',
         'value': 0,
         'event': "xadc",
         'metric': ["temp"],
         'valattr': "value",
      },
      'VCCINT' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vccint"],
         'valattr': "value",
      },
      'VCCAUX' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vccaux"],
         'valattr': "value",
      },
      'VCCBRAM' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vccbram"],
         'valattr': "value",
      },
      'VREFP' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vrefp"],
         'valattr': "value",
      },
      'VREFN' : {
         'prec' : 3,
         'mdel': -1,
         'scan' : 1,
         'unit': 'V',
         'value': 0,
         'event': "xadc",
         'metric': ["vrefn"],
         'valattr': "value",
      },
      'IDCODETEST:RESULT' : {
         'type': 'int',
         'mdel': -1,
         'scan' : 1,
         'value': 0,
         'event': "idcode_test",
         'metric': ["jtag_only"],
         'valattr': "result",
      },
      'UPSETS' : {
         'type': 'int',
         'mdel': -1,
         'scan' : 1,
         'value': 0,
         'event': "count",
         'metric': ["rdcheck_complete", "emptycheck_complete", "overall"],
         'valattr': "upsets",
      },
      'FRAMES' : {
         'type': 'int',
         'mdel': -1,
         'scan' : 1,
         'value': 0,
         'event': "count",
         'metric': ["rdcheck_complete", "emptycheck_complete", "overall"],
         'valattr': "frames",
       },
   },          # end of artix7
}

